-- Create Variables
SET VARIABLE DATA_PATH = '/path/to/parquets/';

-- Create Macros
CREATE OR REPLACE MACRO ARRAY_AGG_DISTINCT(col) AS COALESCE(ARRAY_AGG(DISTINCT col) FILTER (WHERE col IS NOT NULL), []);
